# PHYS 325 Scientific Computing -- Fall 2018

## 1.3 Review of / Introduction to Python basics

Some useful Python online tutorials:

[Tutorial from Python documentation](https://docs.python.org/3/tutorial/)

[A (very short) introduction to Python](http://scipy-lectures.org/intro/index.html)

[Collection of tutorials with quizzes](https://www.programiz.com/python-programming)

### 1.3.1 Features of Python

- easy to learn and use: fast development
- very readable and high-level coding
- object oriented
- interpreter: no compiling (also means considerably slower than eg C++)
- no explicit variable names: extremely polymorphic (has pros and cons)
- forces you to indent properly
- extendible to other languages, good "glue" language for C++ components (esp. for manipulating large numbers of files)
- open source and free (unlike Matlab)
- available for Windows, Unix, OS X (often included by default)
- relatively easy installation on multiple platforms
- large community of users => many online resources
- supported by many packages (science, numerics, graphics, ...)

### 1.3.2 Ways to use Python

- Interactively in a terminal: <br>
    type e.g. ```python``` or ```python3``` or ```python2.7```
- Using an [IDE](https://en.wikipedia.org/wiki/Integrated_development_environment) (Integrated Development Environment), such as [Spyder](https://en.wikipedia.org/wiki/Spyder_(software)<br>
(can use them as glorified editor, or actually run code)
- Inside a Jupyter notebook

In [ ]:
a = 5
b = 9
a*b+100

In [ ]:
print("hello, world!")

#### Making executable Python scripts

- The Python code is saved in a text file, convention for the file ending is ```.py```
- You need to specify in the first line of the program which Python interpreter will be used.
- On Linux this line usually reads<br>
```#!/usr/bin/env python```
- This line has the format of a comment (starts with ```#```) and is treated as such if the program is executed with<br>
```python myProgram.py```
- When executing as<br>
  ```./myProgram.py```<br>
  the first line beginning with ```#!``` tells the operating system to use the program specified in the rest of the first line to interpret the program. In this example, we use the default Python on your system.
- You can also set the path to a specific Python interpreter:<br>
```#!/path/to/special/python```
- ```#!/usr/bin/env python``` finds out automatically where your Python interpreter is; most likely ```#!/usr/bin/python``` on Linux or ```/usr/local/bin/python3``` on Mac, so you can input it directly. You can also find where Python is called from by typing ```which python``` or ```which python3``` etc. into the command line
- IDEs will often automatically insert this line at the beginning of a file

### 1.3.3 Data types

- numerical types
    - integers
    - floats
    - complex numbers (native to Python!)

In [ ]:
myComplexNumber = 1.5 + 0.5j

In [ ]:
print(myComplexNumber.real)
print(myComplexNumber.imag)
print(abs(myComplexNumber))          # example of a basic math function
print(myComplexNumber.conjugate())

- booleans: ```True```, ```False```

In [ ]:
3 <= 4

In [ ]:
3 > 4

In [ ]:
test = (3 > 4)
test

In [ ]:
not(test)

In [ ]:
True and False

In [ ]:
True & False

In [ ]:
True or False

In [ ]:
True + True

- strings => sequence data type

In [ ]:
name = 'Python'
value = "$7.00"
helptext = """You can create long strings of text
spanning several lines by using triple quotes at
the beginning and end of the text"""

In [ ]:
print(helptext)

Ways to escape

In [ ]:
print('doesn\'t')
print("doesn't")
print('"Yes," they said.')
print("\"Yes,\" they said.")
print('"Isn\'t," they said.')

For a list of special characters, see e.g. [here](https://linuxconfig.org/list-of-python-escape-sequence-characters-with-examples)

String arithmetics:

In [20]:
3 * 'great' + 'grandfather'

'greatgreatgreatgrandfather'

In [21]:
word = 'Python'
word[3]         # subject of the next section!

'h'

#### Type conversion

- In Python you can explicitly convert from one type to another:
- Python automatically makes text a string!!!!

In [ ]:
myString = '42'
type(myString)

In [ ]:
myInteger = int(myString)
print(myInteger)
type(myInteger)

In [ ]:
myFloat = float(myInteger)
print(myFloat)
type(myFloat)

- often conversion is performed implicitly:

In [ ]:
print(type(3),type(2))
print(3/2)
print(type(3/2))

In [ ]:
print(type(True))
print(True + True)
print(type(True + True))

### 1.3.4 Sequence types

Most important: list (ordered sequence of items)

In [1]:
mixedList = [1, 2.2, 'python'] #this is a list different naming convention from "array"
mixedList

[1, 2.2, 'python']

In [2]:
mixedList[0]  # indexing returns the item, count starts at 0

1

In [3]:
mixedList[2]

'python'

In [4]:
mixedList[2][0] #you can choose different items from a list acting like a list in iteself
#this allows you to choose different parts of things if needed

'p'

In [5]:
word = mixedList[2] #you can go even deeper by making a list and specific part of it and make it a new variable
word[0]

'p'

In [6]:
word[-1]   # last element: Convient for when you don't know how long a list is

'n'

In [7]:
word[5]

'n'

 ```
 +---+---+---+---+---+---+
 | p | y | t | h | o | n |
 +---+---+---+---+---+---+
 0   1   2   3   4   5   6
-6  -5  -4  -3  -2  -1```

In [8]:
squares = [1, 4, 9, 16, 25]
print(squares)

[1, 4, 9, 16, 25]


**Slicing** returns a new list:

In [13]:
print(squares[1:3]) #Since we count starting at 0 it prints 4 but not 16 because the last element in non-inclusive
print(squares[2:]) #This will start at the second element and print everything after it
print(squares[:]) #This one will print everything in the list

[4, 9]
[9, 16, 25]
[1, 4, 9, 16, 25]


In [15]:
moreSquares = squares + [36, 49, 64, 81, 99] #Adding more elements to the end of the list
moreSquares

[1, 4, 9, 16, 25, 36, 49, 64, 81, 99]

In [16]:
moreSquares[-1] = 100      # replace the wrong value...Using the backwards counting method previously mentioned
moreSquares

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [19]:
moreSquares[2:4] = [0]    # replace several values at once, can be different length
moreSquares #Second element not including and removing the fourth element which is 16

[1, 4, 0, 36, 49, 64, 81, 100]

Built in methods and functions:

In [23]:
moreSquares.append(11**2) #By default the .append() will add the value inputed to the end of the list
moreSquares #You can use .insert() to put anything anywhere in a list

[1, 4, 0, 36, 49, 64, 81, 100, 121]

In [24]:
len(moreSquares) #len() gives the number of items in an object. This does not count starting from 0 since that is used for items

9

Now try the same with string 'python':

In [25]:
word[0]='P'

TypeError: 'str' object does not support item assignment

Strings are **immutable**
(numbers and booleans are also immutable)

But we can create a new string!

In [30]:
newWord = word.replace('p','P',1) #The only way to change something in a list is with the .replace() command .replace(old, new, count)
newWord #old – old substring you want to replace.
        #new – new substring which would replace the old substring.
        #count – the number of times you want to replace the old substring with the new substring. (Optional)

'Python'

Tuples:
- immutable lists
- used to write-protect data 
- usually faster than list, since it cannot change dynamically

In [31]:
myTuple = (5,'program', 1+3j)
print(myTuple)

(5, 'program', (1+3j))


In [33]:
myTuple[1] = 'P'

TypeError: 'tuple' object does not support item assignment

Range:
- immutable sequence type
- useful for iterations

Make a list from 0 (included) to 5 (not included):

In [ ]:
range(5)

In [ ]:
list(range(5))

In [ ]:
list(range(-10,10))

Not covered: sets, dictionaries

### 1.3.5 Assignment

setting a name to hold a **reference** to some object

The first assignment to a variable creates it:
- variable types do not need to be declared like in Java or C++
- Python figures out the variable types on its own

In [ ]:
type(3)                     # the type of the object 3 is integer

In [ ]:
myInteger = 3               # now we assign the object 3 to the variable myInteger
                            # in other words: the name myInteger now refers to 3
                            # by doing this we automatically created the variable myInteger
type(myInteger)             # it has the same type as the object, namely integer

In [ ]:
myInteger = 'isStringNow'   # we can assign a different object to the same variable
type(myInteger)             # now myInteger refers to a string

In [ ]:
myInteger = [1, 2, 3] 
type(myInteger)             # now myInteger refers to a list

> [In Python] A variable is analogous to a sticky note with a name written on it: assigning a value to a variable is like putting that sticky note on a particular value

from [Software Carpentry tutorial](https://swcarpentry.github.io/python-novice-inflammation/01-numpy/)

A reference is deleted via garbage collection after any names bound to it have passed out of scope.

#### Multiple assignment: 

In [ ]:
x, y = 2, 3
s = t = 1
print(x,y,s,t)

#### A closer look

In [22]:
a = "banana"
b = a

<center> Option 1 </center> | <center> Option 2 </center>
--- | ---
![assignment option 1](images/refdiag1.png) | ![assignment option 2](images/refdiag2.png)

*Image credit*: https://runestone.academy/runestone/books/published/fopp/TransformingSequences/ObjectsandReferences.html

In [ ]:
# let's check which one is the case
print(a is b)

In [ ]:
# another way is to explicitly print the unique id that Python assigns to every object
# you can think of this id as essentially specifying the location of the object in computer memory
print(id(a))
print(id(b))

- unlike languages such as C and C++, Python does not allocate a new block of memory for the variable ```b```
- instead ```b``` refers to the same memory location as ```a``` (Option 2)

This has interesting consequences:

#### Deep vs. shallow copies

In [ ]:
a = 3
b = a            # a and b both refer to 3
print(a,b)
print(a is b)

In [ ]:
a = 5            # a now refers to 5
print(a,b)       # a and b are not longer the same
print(a is b)

Can you think of why?

![Python memory assignment](images/variable_memory.gif)
*Image credit*: https://www.python-course.eu/variables.php

Let's try the same with a list:

In [ ]:
a = [1, 2, 3]    # a now references the list [1, 2, 3]
b = a            # b now references what a references
print(a,b)
print(a is b)

In [ ]:
a.append(4)      # this changes the list that a references 
print(a,b)       # what b references has also changed!
print(a is b)

![deep vs. shallow copy](images/deep_shallow_copy.png)

*Slide credit:* [Lode Pollet](https://www.theorie.physik.uni-muenchen.de/lsschollwoeck/members/professors/pollet/index.html)

Examples how to get a deep copy of a list in Python:

In [ ]:
a = [1, 2, 3]
b = a[:]
c = list(a)

a.append(4)
print (a, b, c)

### 1.3.6 Control flow

Conditional expressions with ```if/elif/else``` statements:

In [ ]:
if 2**2 == 4:
    print('Obvious!')

In [ ]:
a = -110

In [ ]:
if a > 0:
     print('Positive')
else:
     print('Not strictly positive')

In [ ]:
if a < 0:
    a = 0
    print('Negative input changed to zero')
elif a > 0:
    print('A strictly positive input')
elif a > 1:
    print('This message will never be printed')
else:
    print('The input is zero')

- comparison operators: ```>```,  ```<```, ```<=```, ```>=```, ```==```, ```!=```
- only one of the ```if/elif/else``` statements is executed
- elif and else are optional (else is the default)
- note the syntax, especially indentation! => will be discussed more later

Loops:
- way to implement repetitive operations
- ```while``` loop:

In [ ]:
a = 0
while a < 6:
    print(a)
    a += 1

![while loop flow chart](images/whileLoopFlowchart.jpg)

*Image from*: https://www.programiz.com/python-programming/while-loop

- ```for``` loop:

In [ ]:
for i in range(6):
    print(i)

![for loop flow chart](images/forLoop.jpg)

*Image from*: https://www.programiz.com/python-programming/for-loop

More examples of ```for``` loop syntax:

In [ ]:
myList = [0,1,2,3,4,5]
for i in myList:
    print(i)

In [ ]:
for i in range(len(myList)):
    print(i)

In [ ]:
for i in 'Python':
    print(i)

- ```break``` and ```continue``` statements:

In [ ]:
myList = ['python','is','not','awesome','at','all']
for i in myList:
    print(i)

In [ ]:
for i in myList:
    if i == 'not':
        continue
    print(i)
    if i == 'awesome':
        break

- The ```break``` statement breaks out of the **innermost enclosing** ```for``` or ```while``` loop. The loop terminates.
- The ```continue``` statement skips the rest of the code inside a loop for the **current iteration only**. The loop does not terminate but continues with the next iteration.

<center> flowchart ```break``` </center> | <center> flowchart ```continue``` </center>
--- | ---
![break flow chart](images/break-statement-flowchart.jpg) | ![continue flow chart](images/continue-statement-flowchart.jpg)

*Images from*: https://www.programiz.com/python-programming/break-continue

- ```else``` clauses can also be used on loops!

In [ ]:
for n in range(2, 10):
    for x in range(2, n):
        if n % x == 0:
            print(n, 'equals', x, '*', n//x)
            break
    else:
        # loop fell through without finding a factor
        print(n, 'is a prime number')

- the ```else``` statement is executed when the loop terminates through exhaustion of the list (```for```) or when the condition becomes false (```while```), but not when the loop is terminated by ```break```

Not covered: zip, pass, enumerate, list comprehension

### 1.3.7 Functions

- we have already seen some pre-defined basic functions:

In [ ]:
x = -4
print(type(x))
print(abs(x))

- you can also define your own functions
- a function in programming is not the same as a mathematical function
- it's a "code package" that performs a specific task and can be used in different parts of your program (or different programs)
- a function can have zero, one, or several arguments (input values)
- a function can return an object (optional)

In [ ]:
# function with zero arguments and no return statement
def test():
    print('my first function')
    
# function with one argument and a return statement
def square(x):
    return x*x

# multiple return statements
def sign(x):
    if x < 0:
        return -1
    elif x > 0:
        return 1
    else:
        return 0
    
# multiple return values (understood as a tuple)
def abs_and_sign(x):
    return abs(x), sign(x)

# a function can have default arguments (rightmost arguments)
def power_of_number(x, power = 2):
    return x**power    

# convenient: keyword arguments
def vertical_position(t = 1, v0 = 0):
    g = 9.81
    return v0*t - 0.5*g*t**2

# recursive functions
def factorial(n):
    if n < 0:
        print("The input is negative")
    elif n <= 1:
        return 1
    else:
        return n*factorial(n-1)

In [ ]:
factorial(5)

- the function arguments are copied when the function is called
- for types such as ```int```, ```float```, ```complex``` the **value** is copied
- shallow copy of sequence types, such as list

In [ ]:
def try_to_modify(x, y, z):
    x = 23
    y.append(42)
    z = [99]      # new reference
    print(x)
    print(y)
    print(z)

a = 77            # immutable variable
b = [99]          # mutable variable
c = [28]
try_to_modify(a, b, c)
print(a)
print(b)
print(c)

Not covered: variable number of arguments, global keyword, lambda

### 1.3.8 Modules

In [1]:
# this illustrates the basic usage of a module in python
# we load the math module which contains pi and print it to the screen
import math
print("pi = ", math.pi)
# print("pi = ", pi) doesn't work

pi =  3.141592653589793


- Collections of variables and functions that logically belong together can be grouped in a separate file called a *module*.
- Modules are thus a good way to organize code in a hierarchical way.
- They can be imported as ```import <module>``` usually at the beginning of the program.
- After ```import math``` we can access all functions in this module, such as<br>
  ```sqrt```, ```sin```, ```cos```, ```exp```,...<br>
  but also constants, such as ```pi```
- You can look up a list of all these functions and constants in the [Python documentation](https://docs.python.org/3/library/math.html)
- To access complex number versions of many of these functions you need to ```import cmath```
- To access the functions and constants you need to preface with ```<module>.``` e.g. ```math.cos(x)```
- If you only need one or few specific functions you can also<br>
  ```from math import sin, cos```<br>
  and then you do not have to preface with ```math.```
- You can also do this: ```from math import *``` (like using a namespace in C++), but this is not recommended due to potential clashes with other modules.
- And you can call a module using a different name. For example if ```math``` is too long for you, you can:<br>
  ```import math as mth```<br>
  then you call ```mth.cos(x)``` etc.
- You can check out the full list of [Python standard modules](https://docs.python.org/3/py-modindex.html) -- there are lots! We will discuss several of them as we advance in the course.
- You can also easily make your own modules! => splitting your project into several files<br>
  e.g. we can put our ```factorial``` function into the file ```myfunctions.py``` and import it via ```import myfunctions``` or ```from myfunctions import factorial``` etc.

### 1.3.9 Syntax

- indentation is compulsory (not just for good style)
- no brackets like in C++ or Java
- indentation must be consistent
- convention: always 4 spaces
- Python 3 disallows mixing the use of tabs and spaces for indentation

You can find the complete and very detailed [Python style guide here.](https://www.python.org/dev/peps/pep-0008/)

**Names:**
- are case sensitive
- may contain numbers but cannot start with a number
- may not contain any special characters except ```_``` (names can start with ```_```)
- reserved words: ```and, assert, break, class, continue, def, del, elif, else, except, exec, finally, for, from, global, if, import, in, is, lambda, not, or, pass, print, raise, return, try, while```
- you can overwrite anything else...

**Comments:**

In [ ]:
# This is a demonstration of comments in Python

a = 0   # this is a comment

text = "# This is not a comment because it's inside quotes."

# For comments that go over multiple lines
# most editors let you comment and uncomment
# a block of text at once

def some_function():
    """
    Text between triple quotes is also handled as a type of comment.
    It is called "docstring" and is typically used to explain what a 
    program, function, module or class does. 
    Docstrings can be turned into documentation. 
    """
    print("some output")

**Line formatting:**
- can put several commands in one line using ```;``` (usually bad style)
- no need to mark the end of a line (e.g. with ```;``` like in C++)
- break long lines with \
- often there is a ```:``` at the start of a new block

In [ ]:
x = 1; y = 2; z = x + y; print(z)   # can put several commands in one line using ";"

In [ ]:
# very long piece of code
sum = x + x**2/2 + x**3/3 + x**4/4 + x**5/5 + x**6/6 + x**7/7 + x**8/8 + x**9/9

# split using parentheses ...
sum = (x + x**2/2 + x**3/3
     + x**4/4 + x**5/5
     + x**6/6 + x**7/7
     + x**8/8 + x**9/9)

# or the line continuation operator (more general method)
sum = x + x**2/2 + x**3/3 \
    + x**4/4 + x**5/5 \
    + x**6/6 + x**7/7 \
    + x**8/8 + x**9/9

# The usual convention is to limit lines to a maximum of 79 characters.
# Make sure that there are no spaces after the "\" sign!

A few examples directly comparing Java and Python, taken from [here](https://pythonconquerstheuniverse.wordpress.com/2009/10/03/python-java-a-side-by-side-comparison/):

Loops

<table>
    <tr> 
    <td style="vertical-align:top; text-align: center; width:30em">
        Java</td>
    <td style="vertical-align:top; text-align: center; width:30em">
        Python </td>
    </tr>  
<tr>
<td style="vertical-align:top; text-align: left; width:20em">
<pre>// print the integers from 1 to 9
for (int i = 1; i &lt; 10; i++)
    {
     System.out.println(i);
    }</pre>
</td>
<td style="vertical-align:top; text-align: left; width:20em">
<pre>
# print the integers from 1 to 9
for i in range(1,10):
    print i</pre>
</td>
</tr>
</table>

If statement:
<table>
    <tr> 
    <td style="vertical-align:top; text-align: center; width:20em">
        Java </td>
    <td style="vertical-align:top; text-align: center; width:20em">
        Python </td>
    </tr>
<tr>
<td style="vertical-align:top; text-align: left; width:20em">
<pre>
if ( a > b )
    {
     a = b;
     b = c;
    }
</pre>
</td>
<td style="vertical-align:top; text-align: left; width:20em">
<pre>
if  a > b :
    a = b
    b = c
</pre>
</td>
</tr>
</table>

List manipulation:
<table>
    <tr> 
    <td style="vertical-align:top; text-align: center; width:62em">
        Java (after version 1.5) </td>
    <td style="vertical-align:top; text-align: center; width:30em">
        Python </td>
    </tr>    
<tr>
<td style="vertical-align:top; text-align: left; width:62em">
<pre>public Vector&lt;Integer&gt; aList = new Vector&lt;Integer&gt;;
public int aNumber = 5;
public int anotherNumber;

aList.addElement(aNumber);
anotherNumber = aList.getElement(0);</pre>
</td>
<td style="vertical-align:top; text-align: left; width:30em">
<pre>aList = []
aNumber = 5

aList.append(aNumber)
anotherNumber = aList[0]</pre>
</td>
</tr>
</table>

### 1.3.10 Data input and output

- the most basic output is ```print(myString)``` which we have already seen
- you can format the output more nicely/conveniently:

In [ ]:
print('{} and {}'.format('spam', 'eggs'))
print('{0} and {1}'.format('spam', 'eggs'))
print('{1} and {0}'.format('spam', 'eggs'))
print('This {food} is {adjective}.'.format(
       food='coffee', adjective='absolutely horrible'))

In [ ]:
for x in range(1, 11):
    print('{0:2d} {1:3d} {2:4d}'.format(x, x*x, x*x*x))

In [ ]:
from math import pi
print(pi)
print('Pi showing only the first 5 digits: %.5f' % pi)

- command line input:

In [2]:
inputNumber = input("Enter a positive number: ")
type(inputNumber)

Enter a positive number:  3


str

In [3]:
inputNumber = int(input("Enter a positive number: "))
type(inputNumber)

Enter a positive number:  3


int

- manipulating files:

In [4]:
f = open('workfile', 'w')  # write only, creates a file if it doesn't exist or overwrites
f.write('This is a test \n and another test')
f.close()

In [5]:
f = open('workfile', 'r')  # read only
s = f.read()
print(s)
f.close()

This is a test 
 and another test


In [ ]:
f = open('workfile')       # default is read only (in text mode)
for line in f:
    print(line)
f.close()

- there are many additional methods for reading, examining, and manipulating files
- the numpy library also has useful file methods => see next section

### 1.3.11 Libraries

[NumPy](http://numpy.org/): creating and manipulating numerical data:
- powerful linear algebra tools
- fast array operations
- useful Fourier transform and random number capabilities
- tools for integrating C/C++/Fortran code
- also very efficient for handling generic multi-dimensional data
- reference: https://docs.scipy.org/doc/numpy/reference/
- tutorials: 
     - http://www.scipy-lectures.org/numpy/numpy.html
     - https://docs.scipy.org/doc/numpy/user/quickstart.html

Here are some examples:

In [3]:
import numpy as np        # standard alias
a = np.array([0, 1, 2])   # compare to a list of elements of the same type
a

array([0, 1, 2])

In [4]:
print(a)

[0 1 2]


In [5]:
a + a                     # unlike for regular lists, the *elements* are now added

array([0, 2, 4])

In [6]:
b = np.array([[0., 1.], [2., 3.]])
b

array([[0., 1.],
       [2., 3.]])

In [7]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
b = np.arange(1., 9., 2)    # syntax: start, end, step
b

array([1., 3., 5., 7.])

In [12]:
c = np.arange(0, 1, 0.5)
c

array([0. , 0.5])

In [10]:
x = np.linspace( 0, 2*np.pi, 20 )   # numpy also has math functionalities
f = np.sin(x)                       # useful to evaluate function at lots of points
print(f)

[ 0.00000000e+00  3.24699469e-01  6.14212713e-01  8.37166478e-01
  9.69400266e-01  9.96584493e-01  9.15773327e-01  7.35723911e-01
  4.75947393e-01  1.64594590e-01 -1.64594590e-01 -4.75947393e-01
 -7.35723911e-01 -9.15773327e-01 -9.96584493e-01 -9.69400266e-01
 -8.37166478e-01 -6.14212713e-01 -3.24699469e-01 -2.44929360e-16]


In [ ]:
a = np.ones((3,3))
a

In [ ]:
b = np.ones(5, dtype=np.int)
b

In [ ]:
c = np.zeros((2,2))
c

In [ ]:
d = np.eye(3)
d

In [ ]:
a = np.arange(15).reshape(3, 5)
a

In [ ]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.sum())
print(a.sum(axis = 0))
print(a.max())

An illustrated summary of Numpy indexing and slicing

![numpy indexing and slicing](images/numpy_indexing.png)

Source: http://www.scipy-lectures.org/numpy/numpy.html

A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. When modifying the view, the original array is modified as well:

In [ ]:
A = np.array( [[1,1],
               [0,1]] )
A.transpose()

In [ ]:
B = np.array( [[2,0],
               [3,4]] )
A * B                       # elementwise product

In [ ]:
A.dot(B)                    # matrix product

In [ ]:
# the following modify the existing array
A *= 3
print(A,'\n')
A += B
print(A)

Writing and reading a file:
- Writing a text file (in ASCII):

In [ ]:
np.savetxt('data_A.txt', A)

- Writing a binary file (.npy extension, recommended format)

In [ ]:
np.save('data_B.npy', B)

- Reading from a text file:

In [ ]:
b = np.loadtxt('data_A.txt')
b

- Reading from a binary file:

In [ ]:
c = np.load('data_B.npy')
c

In [ ]:
for s1 in range(2):
    for s2 in range(2):
        filename="input_files/P_%d_%d.dat" % (s1, s2)
        data = np.loadtxt(filename)
        print(s1, s2, data)
data

There are a lot more features => documentation, references, internet search

[Scipy](https://www.scipy.org/):
- The SciPy library provides many user-friendly and efficient numerical routines e.g. for numerical integration and optimization.
- Scipy builds on Numpy, and for all basic array handling needs you can use Numpy functions
- Tutorials: 
     - https://docs.scipy.org/doc/scipy/reference/tutorial/index.html
     - http://www.scipy-lectures.org/scipy.html

A few examples:

- special functions of mathematical physics: submodule scipy.special<br>
  Bessel function, Gamma function, etc.

In [ ]:
from scipy import special
help(special)

- scipy.integrate
- scipy.linalg contains all the functions in numpy.linalg plus additional ones (and might be faster depending on numpy installation)
- scipy.interpolate
- ...and many more

### 1.3.12 Plotting 

[matplotlib](http://matplotlib.sourceforge.net):
- high quality plotting library
- "makes easy things easy and hard things possible"
- can also be used interactively with IPython
- many tutorials on the matplotlib website, e.g.<br>
  https://matplotlib.org/tutorials/index.html
  and references to additional resources:<br>
  https://matplotlib.org/resources/index.html

Example script illustrating the most important matplotlib features:

In [ ]:
%matplotlib inline

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Data for plotting (you can also load from a file with numpy)
xvalues = np.arange(0.0, 2.0, 0.01)          # this generates a fine list of numbers for plotting 
def function1(x):                            # this is a function that we want to plot
    return 1 + np.sin(2 * np.pi * x)
yvalues2 = 1 + np.cos(2 * np.pi * xvalues)   # this is another function, here saved explicitly into a list

# custom plot range, if desired
plt.xlim([-0.5,2.0])  
plt.ylim([0.0,2.8])

# the actual plot, specifying line styles
plt.plot(xvalues, function1(xvalues), 'r--', linewidth=2, label='function 1')
plt.plot(xvalues, yvalues2, 'b-', linewidth=2, label='function 2')

# additional horizontal line with a few plotting options
plt.axhline(y=1, color='black', linestyle='-', linewidth=1)

# Plot title, axes labels, and legend with a few example options
plt.title('The title of the plot')
plt.xlabel('x-axis label')
plt.ylabel('y-axis label', fontsize=16)
plt.legend(loc='upper right', frameon=False, fontsize=16, labelspacing=0.3)

# include this command if you want to display a grid
plt.grid()

# this saves all components of the plot into a file
plt.savefig("test.png")

# this displays all components of the plot
plt.show()

Not covered in this lecture: errors and exceptions, object oriented programming, virtual environment