# Exercise 1

For the non-reduced function y you have roundoff errors in the first part and then you are subtracting from the second part making the error larger

In [3]:
import math

x = 10**-5
num = 2*x**2
den = 1+3*x+2*x**2

y = num/den

print(y)

1.9999400013999704e-10


# Exercise 2

In [16]:
#Kaleb Kautzsch
import scipy as sp
import scipy.linalg as la
import numpy.linalg as nl

#Recreating the array from Exercise 2
A1 = sp.array([[2,4,6],[-1,0,1],[1,2,3]])
A2 = sp.array([[3,4,5],[1,0,-1],[2,2,2]])
b = sp.array([12,0,6])

#Solving for the permutatiion, lower diagonal, and upper diagonal Part (a)
P, L, U = la.lu(A1)
p, l, u = la.lu(A2)

#Solving for x using two different ways
# x1 = la.solve(A1,b)
# x2 = la.solve(A2,b)
x3 = la.lstsq(A1,b)
x4 = la.lstsq(A2,b)

#Compute the inverse
# inv1 = la.inv(A1)
# inv2 = la.inv(A2)

#Determinate and rank
d1 = la.det(A1)
d2 = la.det(A2)
r1 = nl.matrix_rank(A1)
r2 = nl.matrix_rank(A2)

print(L, "Lower triangle for A1\n")
print(l, "Lower triangle for A2\n")
print(U, "Upper triangle for A1\n")
print(u, "Upper triangle for A2\n")
print(d1, "Determinate for A1\n")
print(d2, "Determinate for A2\n")
print(r1, "Rank for A1\n")
print(r2, "Rank for A2\n")
#print(inv1, "Inverse for A1\n")
#print(inv2, "Inverse for A2\n")
#print(x1, "Solution using solve function for A1\n")
#print(x2, "Solution using solve function for A2\n")
print(x3, "Solution using lstsq function for A1\n")
print(x4, "Solution using lstsq function for A2")

[[ 1.   0.   0. ]
 [-0.5  1.   0. ]
 [ 0.5  0.   1. ]] Lower triangle for A1

[[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.66666667 0.5        1.        ]] Lower triangle for A2

[[2. 4. 6.]
 [0. 2. 4.]
 [0. 0. 0.]] Upper triangle for A1

[[ 3.00000000e+00  4.00000000e+00  5.00000000e+00]
 [ 0.00000000e+00 -1.33333333e+00 -2.66666667e+00]
 [ 0.00000000e+00  0.00000000e+00 -7.40148683e-17]] Upper triangle for A2

-6.661338147750939e-16 Determinate for A1

0.0 Determinate for A2

2 Rank for A1

2 Rank for A2

(array([1., 1., 1.]), array([], dtype=float64), 2, array([8.38408352e+00, 1.30657706e+00, 1.19439988e-16])) Solution using lstsq function for A1

(array([1., 1., 1.]), array([], dtype=float64), 2, array([7.85269342e+00, 1.52813810e+00, 1.96571502e-16])) Solution using lstsq function for A2
