In [3]:
#Kaleb Kautzsch
import scipy as sp
import scipy.linalg as la
import numpy.linalg as nl

#Recreating the array from Exercise 2
A1 = sp.array([[2,4,6],[-1,0,1],[1,2,3]])
A2 = sp.array([[3,4,5],[1,0,-1],[2,2,2]])
b = sp.array([12,0,6])

#Solving for the permutatiion, lower diagonal, and upper diagonal Part (a)
P, L, U = la.lu(A1)
p, l, u = la.lu(A2)

#Solving for x using two different ways
# x1 = la.solve(A1,b)
# x2 = la.solve(A2,b)
x3 = la.lstsq(A1,b)
x4 = la.lstsq(A2,b)

#Compute the inverse
# inv1 = la.inv(A1)
# inv2 = la.inv(A2)

#Determinate and rank
d1 = la.det(A1)
d2 = la.det(A2)
r1 = nl.matrix_rank(A1)
r2 = nl.matrix_rank(A2)

# print(L, "Lower triangle for A1\n")
# print(l, "Lower triangle for A2\n")
# print(U, "Upper triangle for A1\n")
# print(u, "Upper triangle for A2\n")
# print(d1, "Determinate for A1\n")
# print(d2, "Determinate for A2\n")
# print(r1, "Rank for A1\n")
# print(r2, "Rank for A2\n")
# print(inv1, "Inverse for A1\n")
# print(inv2, "Inverse for A2\n")
# print(x1, "Solution using solve function for A1\n")
# print(x2, "Solution using solve function for A2\n")
print(x3, "Solution using lstsq function for A1\n")
# print(x4, "Solution using lstsq function for A2")

(array([1., 1., 1.]), array([], dtype=float64), 2, array([8.38408352e+00, 1.30657706e+00, 1.19439988e-16])) Solution using lstsq function for A1



In [3]:
eigValues, eigVectors = la.eig(A2)
print(sp.dot(A2, eigVectors[:,2]),'Null Space\n')
print(sp.dot(A2, sp.array([[4],[-5],[4]])), 'Check to make sure general solution works \n')
print(eigValues,'Eigen Values \n')
print(eigVectors,'Eigen Vectors')

[-2.22044605e-15  3.33066907e-16 -8.88178420e-16] Null Space

[[12]
 [ 0]
 [ 6]] Check to make sure general solution works 

[ 6.00000000e+00+0.j -1.00000000e+00+0.j -1.23962303e-15+0.j] Eigen Values 

[[-8.78458592e-01 -7.07106781e-01  4.08248290e-01]
 [-6.75737378e-02  7.07106781e-01 -8.16496581e-01]
 [-4.73016165e-01 -4.22538650e-16  4.08248290e-01]] Eigen Vectors


In [4]:
print(la.null_space(A2), 'Null Space\n')

[[ 0.40824829]
 [-0.81649658]
 [ 0.40824829]] Null Space



In [5]:
U, S, Vh, = la.svd(A2)
U.shape, S.shape, Vh.shape

((3, 3), (3,), (3, 3))

In [6]:
print(U.transpose(), 'U Transpose\n')
diag = sp.array([[1/S[0],0,0],[0,1/S[1],0],[0,0,0]])
first = sp.dot(Vh.transpose(),diag)
second = sp.dot(U.transpose(),b)
x = sp.dot(first,second)
print(x, 'Mother flippin solution')

[[-0.89997218  0.03016761 -0.43490228]
 [ 0.15291636 -0.91237232 -0.37972798]
 [-0.40824829 -0.40824829  0.81649658]] U Transpose

[1. 1. 1.] Mother flippin solution


# Hail Cthulhu


In [7]:
from matplotlib.image import imread
from matplotlib.pyplot import imshow
import matplotlib.pyplot as plt

image = imread('Cthulhu.jpg')

In [8]:
u, s, vh = nl.svd(image)
plt.imshow()

MemoryError: 